name = "D4M"
uuid = "ca196bdc-a701-11e8-3d50-3b5cc8577617"
authors = ["Lauren <lauren.milechin@mit.edu>", "Nathan <nkim8@mit.edu>"]
version = "0.3.3"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JavaCall = "494afd89-becb-516b-aafa-70d2670c0337"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
